---
title: "DSAVE Cell-wise Variation"
author: "Juan Inda"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DSAVE-R Total Variation}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---


```{r}
library(ggplot2)
library(DSAVE)
```


## Cell-wise variation from single cell data.

- Download the B cells data set.

```{r}
bcells <- LoadAndDownloadBCells()
```

- Subsample to 1000 cells and run DSAVEGetSingleCellDivergence

```{r}
bcells_id <- sample(1:dim(bcells)[2], 1000)
bcells_cell_divergence <- DSAVEGetSingleCellDivergence(bcells[,bcells_id], minUMIsPerCell = 200, tpmLowerBound = 0, iterations = 15, silent=FALSE)
```

- Plot the results

```{r}
numUMIshcatSub2 <- colSums(as.matrix(bcells[,bcells_id]))
linevalYs <- seq(from =  500, to = 10500, by = 250)
linevalXes <- rep(0, length(linevalYs))
for(i in 1:length(linevalYs)){
  ii <- linevalYs[i]
  lb <- ii - 250
  ub <- ii + 250
  sel <- numUMIshcatSub2 >= lb & numUMIshcatSub2 <= ub
  if(sum(sel)!=0){
    linevalXes[i] <- mean(bcells_cell_divergence[sel])
  }else{
    linevalXes[i] <- NA
  }
}
linevalYs <- c(linevalYs, rep(NA, length(numUMIshcatSub2) - length(linevalYs)))
linevalXes <- c(linevalXes, rep(NA, length(numUMIshcatSub2) - length(linevalXes)))
linevalYs[is.na(linevalXes)] <- NA
id <- order(linevalYs, decreasing = F)
linevalXes <- linevalXes[id]
linevalYs <- linevalYs[id]


df <- as.data.frame(cbind(bcells_cell_divergence, colSums(as.matrix(bcells[,bcells_id]))))
ggplot(df, aes(x=bcells_cell_divergence, y=V2, colour = "Individual cell")) + 
  geom_point() +
  ggtitle("UMI Counts vs Cell Divergence") +
  xlab("Log-likelihood") + ylab("UMI counts") +
  theme(legend.justification = c(1, 1),
        legend.title=element_blank(),
        legend.position = c(1, 1),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 10)) +
  geom_path(aes(linevalXes, linevalYs, colour="Mean log-likelihood"))


id <- order(bcells_cell_divergence, decreasing = F)
df <- as.data.frame(cbind(1:length(bcells_cell_divergence), bcells_cell_divergence[id]))
ggplot(df, aes(x=V1, y=V2, colour = "B cells")) + 
  geom_line() +
  ggtitle("Cell Divergence") +
  xlab("Cell index") + ylab("Log-likelihood") +
  theme(legend.justification = c(1, 0),
        legend.title=element_blank(),
        legend.position = c(1, 0),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 10))
```
