---
title: "DSAVE Gene-wise Variation"
author: "Juan Inda"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DSAVE-R Gene-wise Variation}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---


```{r}
library(ggplot2)
library(DSAVE)
```


## Gene-wise variation from single cell data.

- Download the B cells data set.

```{r}
bcells <- loadOrDownloadB10k()
```

- Run DSAVEGetGeneVariation

```{r}
bcells_gene_variation <- DSAVEGetGeneVariation(as.matrix(bcells), lb=10, iterations = 100, maxNumCells=2000, silent=FALSE)

```

- Plot the results

```{r}
id <- order(bcells_gene_variation$logCVDifference, decreasing = T)

df <- as.data.frame(cbind(1:length(id), 
                          bcells_gene_variation$logCVDifference[id]))

ggplot(df, aes(x=V1, y=V2, colour = "B cells")) + 
  geom_line() +
  ggtitle("Variation per Gene") +
  xlab("Gene index") + ylab("BTM variation") +
  theme(legend.justification = c(1, 1),
        legend.title=element_blank(),
        legend.position = c(1, 1),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 10))
```

- Probabilities

```{r}
#It is to be noted that these p values are generated with too few iterations; that is why the 
#graph is not smooth. We recommend at least 10,000 iterations to get proper p values, but that takes
#much longer to run.

pvals <- bcells_gene_variation$pVals
#pvals_adj <- p.adjust(pvals, "BH")
id <- order(pvals, decreasing = T)

df <- data.frame(gene = bcells_gene_variation$genes[id], index = 1:length(pvals[id]), pvals = pvals[id])
df$gene <- as.character(df$gene)
ggplot(df, aes(x=index, y=pvals, colour = "B cells")) + 
  geom_line() +
  ggtitle("p values per gene") +
  xlab("Gene index") + ylab("p value") +
  theme(legend.justification = c(1, 1),
        legend.title=element_blank(),
        legend.position = c(1, 1),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 10))

```
