name: Build vignette and package

on:
  push:
    branches:
      - 'devel'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  run:
    runs-on: ubuntu-18.04
    container:
      image: rstudio/r-base:3.6-bionic
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install system dependencies
        run: |
          sudo apt-get update && apt-get install -y --no-install-recommends \
          libxml2-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          libpng-dev
      - name: Install R package dependencies
        run: R -e "install.packages('devtools', repos='https://cloud.r-project.org'); devtools::install_deps(dependencies = TRUE, build = FALSE, quiet = TRUE)"
      - name: Build and check R package
        run: |-
          R CMD build .
          R CMD check --no-vignettes --no-manual *.tar.gz
      - name: Auto-commit vignette
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: update vignette output html
          branch: devel
          file_pattern: docs/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
