name: CICD

"on":
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: rstudio/r-base:3.6-bionic
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |-
          R -e "install.packages('devtools', repos='http://cran.us.r-project.org')"
          R -e "devtools::install_deps(dep = T)"
        with:
          path: ~/R-library
          key: R-library
      - name: Build package
        run: R CMD build .
      - name: Check package
        run: R CMD check --no-vignettes *.tar.gz
