name: CICD

on:
  push:
    branches:
      - 'devel'
      - 'master'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: rstudio/r-base:3.6-bionic
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Install system dependencies
        run: |
          sudo apt-get update && apt-get install -y --no-install-recommends \
          libxml2-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          libpng-dev
      - name: Install package dependencies
        run: |-
          R -e "install.packages('devtools', repos='http://cran.us.r-project.org')"
          R -e "devtools::install_deps(dep = T)"
      - name: Build package
        run: R CMD build .
      - name: Check package
        run: R CMD check --no-vignettes *.tar.gz
